spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/spring
    username: root
    password: 123456
  druid:
    keep-alive: true
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true